### ISSUE TITLE
大佬，为啥我复制了url，运行一直显示something is wrong 

### ISSUE THREAD

**Issue by fhfhfh773** [CooSei/ssxx#2]

**Comment by CooSei** [comment]
今天自测可用
1.考虑你url获取错误? url获取我在readme文件有写你可以看下
2.所需库是否安装
3.代码里url没加引号?

**Comment by fhfhfh773** [comment]
1.url和示例里的一样
2.我用visual studio 运行的，运行时软件没报缺库
3.我放在引号里
4.运行时显示
1
something is wrong
12
something is wrong
23
something is wrong
34
something is wrong
45
something is wrong
循环了三遍

**Comment by CooSei** [comment]
`import time, requests, json, re
from bs4 import BeautifulSoup



def decrypt(op):
	soup = BeautifulSoup(op, 'lxml')
	soup_text = soup.text
	# p = re.compile(r'display: ?none;">(.*?)<')
	p = re.compile(r'display: ?none;(text-decoration:none;)?">(.*?)<')
	for i in p.findall(op):
		if i:
			soup_text = soup_text.replace(i[1], '')
	return soup_text

if __name__ == '__main__':
	url = 'https://ssxx.univs.cn/cgi-bin/authorize/token/?t=1608904494&uid=5fbb376da8faed8fbba03e7c&avatar=https:%2F%2Fnode2d-public.hep.com.cn%2Favatar-5fbb376da8faed8fbba03e7c-1606104941788'
	this_time = str(int(time.time()))
	my_name = '英雄'
	my_index = '5f71e934bcdbf3a8c3ba51d5'
	q_a = {}
	headers = {
	'Host':'ssxx.univs.cn',
	'Connection': 'keep-alive',
	'Accept': 'application/json, text/plain, */*',
	'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36',
	'Sec-Fetch-Site': 'same-origin',
	'Sec-Fetch-Mode': 'cors',
	'Sec-Fetch-Dest': 'empty',
	'Referer': 'https://ssxx.univs.cn/clientLogin?redirect=%2Fclient%2Fdetail%2F5f71e934bcdbf3a8c3ba5061',
	'Accept-Encoding': 'gzip, deflate, br',
	'Accept-Language': 'zh-CN,zh;q=0.9',
	'Cookie': "_ga=GA1.2.406742327.1606105391; tgw_l7_route=be2f17e6fbcb3e6c5202ac57e388ad5a; _gid=GA1.2.25532619.1608623537; _gat=1",
	}
	response = requests.get(url, headers=headers)
	ll = json.loads(response.text)
	token = ll['token']
	url2 = 'https://ssxx.univs.cn/cgi-bin/race/beginning/?t='+this_time+'&activity_id=5f71e934bcdbf3a8c3ba5061&mode_id='+my_index+'&way=1'
	headers['Authorization'] = 'Bearer '+token
	response = requests.get(url2,headers=headers)
	question = json.loads(response.text)
	question_id = question['question_ids']
	race_code = question['race_code']
	headers['Referer'] = 'https://ssxx.univs.cn/client/exam/5f71e934bcdbf3a8c3ba5061/1/1/'+my_index
	every_score = 20
	with open(my_name+'.txt','a') as f:
		for l in question_id:
			url3 = 'https://ssxx.univs.cn/cgi-bin/race/question/?t='+this_time+'&activity_id=5f71e934bcdbf3a8c3ba5061&question_id='+l+'&mode_id='+my_index+'&way=1'
			a = requests.get(url3, headers)
			all_data = json.loads(a.text)
			title = decrypt(all_data['data']['title'])
			ops = []
			ops_id = []
			for i in range(len(all_data['data']['options'])):
				ops.append(decrypt(all_data['data']['options'][i]['title']))
				ops_id.append(all_data['data']['options'][i]['id'])
			url4 = 'https://ssxx.univs.cn/cgi-bin/race/answer/'
			if q_a.get(l, 0) != 0:
				post_answer = q_a[l]
			else:
				post_answer = [ops_id[0]]
			data = {"activity_id":"5f71e934bcdbf3a8c3ba5061",
					"question_id":l,
					"answer":post_answer,
					"mode_id":my_index,
					"way":"1"
					}
			post_data = requests.post(url4,headers=headers,json=data)
			answer_json = json.loads(post_data.text)
			answer = answer_json['data']['correct_ids']
			word_list = []
			for k in answer:
				word = decrypt(ops[ops_id.index(k)])
				word_list.append(word)
			if q_a.get(l) == 0:
				q_a[l] = answer
			if l not in q_a:
				every_score -= 1
				q_a[l] = answer
				try:
					f.write(title)
				except:
					f.write(title[:12])
				f.write('\n')
				f.write(json.dumps(word_list,ensure_ascii=False))
				f.write('\n')
		url5 = "https://ssxx.univs.cn/cgi-bin/race/finish/"
		race = {"race_code":race_code}
		requests.post(url5, headers=headers, json=race)
`
你试试看这个会报什么错,  其实这个东西本来以为没人看所以就没写注释

**Comment by CooSei** [comment]
你把我上传的[_debug.py](./_debug.py)文件复制运行一下看看哪里有问题(也只需要输入url),本来以为这东西没人看的,就没写注释

**Comment by fhfhfh773** [comment]
抓去新的url填进去，运行是返回这个结果
Traceback (most recent call last):
  File "c:/Users/86176/Desktop/ssxx-main/_debug.py", line 51, in <module>
    title = decrypt(all_data['data']['title'])
  File "c:/Users/86176/Desktop/ssxx-main/_debug.py", line 7, in decrypt
    soup = BeautifulSoup(op, 'lxml')
  File "C:\Users\86176\AppData\Local\Programs\Python\Python38\lib\site-packages\bs4\__init__.py", line 242, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by fhfhfh773** [comment]
谢谢啊，运行了debud.py显示少了lxml库，我安装了，现在已经可以用了

**Comment by fhfhfh773** [comment]
现在运行没问题了，就是每次提交后，返回的分数太低了，大多数都是0，怎么利用抓取到的题库优化下准确率

**Comment by CooSei** [comment]
(1)没事,这个是自动优化的,大约150次左右正确率会上90%,你要确保程序每次正常运行完,以'英雄'举例,程序正常运行结束会生成下面三个文件:
1.<英雄.txt>(这个是给人看的,也是程序的本来目的,程序刷题其实没用)
2.<英雄q_a.txt>(这个用于程序答题)
3.<英雄score.txt>(这个用于记录每次答题分数)
如果中途退出可能只有1有内容;2,3是空的,
(2)如果你是用来刷题的,那我建议:
1.函数中的max_loop值是每个栏目循环的次数,第一次运行时先改为150,之后运行越大越好
2.函数中的max_same越大越好,这个是用于判断分数多少次不变则结束程序的

**Comment by fhfhfh773** [comment]
懂了，谢谢

**Comment by CooSei** [comment]
刚才发现这个网站又修改规则了,所以更新了下[代码](./四史答题.py),
需要安装Levenshtein库(安装方法你百度下)
使用前要把你之前那些文件删除,怕引起冲突

**Comment by fhfhfh773** [comment]
老哥，能不能改下代码，显示每次开始后每轮刷的积分总和，看不见多少分容易刷过头
